package View;

import Persistence1.MSAccess;
import Logic.Product;
import FlatFiles.FlatFileProduct;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Logic.cola1;


/**
 *
 * @author Estudiante
 */
public class InterfazProduct extends javax.swing.JFrame {
    cola1 cl= new cola1();
    private MSAccess dataFile;
    private ImageIcon iconNoPhoto;
    /**
     * Creates new form Interfaz
     */
    public InterfazProduct() {
        initComponents();
        
        labPhotoFilename.setVisible(false);
        this.setIconNoPhoto((ImageIcon)labPhoto.getIcon());

        this.setDataFile(new MSAccess());
        this.selectProduct();
        
        setLocationRelativeTo(null);
    }

   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupGenero = new javax.swing.ButtonGroup();
        panDatosPersonales = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblDate_of_admission = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labPhoto = new javax.swing.JLabel();
        dateDate_of_admission = new com.toedter.calendar.JDateChooser();
        labId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        labPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        labPhotoFilename = new javax.swing.JLabel();
        butPhoto = new javax.swing.JButton();
        ComType = new javax.swing.JComboBox();
        panCrud = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Empleados Usta");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product dates", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panDatosPersonales.setToolTipText("");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setText("Name:");

        lblSex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSex.setText("kind of product:");

        lblDate_of_admission.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate_of_admission.setText("Date of admission:");

        labPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/noPhoto.jpg"))); // NOI18N

        labId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labId.setText("Id:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        labPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labPrice.setText("Price:");

        butPhoto.setText("Load Photo");
        butPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPhotoActionPerformed(evt);
            }
        });

        ComType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "q" }));

        javax.swing.GroupLayout panDatosPersonalesLayout = new javax.swing.GroupLayout(panDatosPersonales);
        panDatosPersonales.setLayout(panDatosPersonalesLayout);
        panDatosPersonalesLayout.setHorizontalGroup(
            panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSex)
                            .addComponent(labId)
                            .addComponent(lblName))
                        .addGap(42, 42, 42)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate_of_admission)
                            .addComponent(labPrice))
                        .addGap(30, 30, 30)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateDate_of_admission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(butPhoto)
                        .addGap(76, 76, 76))
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labPhotoFilename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
        );
        panDatosPersonalesLayout.setVerticalGroup(
            panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSex)
                            .addComponent(ComType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(labPhotoFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butPhoto))
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDate_of_admission)
                            .addComponent(dateDate_of_admission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(panDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 46, 593, -1));

        panCrud.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setText("Search ...");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCrudLayout = new javax.swing.GroupLayout(panCrud);
        panCrud.setLayout(panCrudLayout);
        panCrudLayout.setHorizontalGroup(
            panCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst)
                .addGap(18, 18, 18)
                .addComponent(btnPrevious)
                .addGap(16, 16, 16)
                .addComponent(btnNext)
                .addGap(18, 18, 18)
                .addComponent(btnLast)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(10, 10, 10)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panCrudLayout.setVerticalGroup(
            panCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCrudLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnLast)
                    .addComponent(btnSearch)
                    .addComponent(btnDelete)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnNew)
                    .addComponent(btnUpdate)))
        );

        getContentPane().add(panCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 387, 616, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/X_ico.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Save products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, -1, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 600, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * New Employee record 
     * @param evt 
     */
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       if (btnNew.getText().equals("New")) {
            this.newView();
        }
        else if (btnNew.getText().equals("Save")) {
            if (validateView()) {
                this.insertProduct();

                btnNew.setText("New");
                btnFirst.setEnabled(true);
                btnPrevious.setEnabled(true);
                btnNext.setEnabled(true);
                btnLast.setEnabled(true);
                btnSearch.setEnabled(true);
                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);
            }
            else {
                JOptionPane.showMessageDialog(this, "Please, fill the requeried fields", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


//        cl.encolar(pa);
//        JOptionPane.showMessageDialog(this, "Se ha agregado tu producto con exito");  
//        llenarLista();
        
       
            
    }//GEN-LAST:event_btnNewActionPerformed

    
    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            this.getDataFile().getResultSet().first();
            this.updateView();
        } catch (SQLException ex) {
            Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         try {
            if (!this.getDataFile().getResultSet().isFirst()) {
                this.getDataFile().getResultSet().previous();
                this.updateView();
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       try {
            if (!this.getDataFile().getResultSet().isLast()) {
                this.getDataFile().getResultSet().next();
                this.updateView();
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        long id = Long.parseLong(JOptionPane.showInputDialog(
                "Please, write the product id", "Product id"));
        if (id > 0) {
            this.searchProduct(id);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         this.updateProduct();
        JOptionPane.showMessageDialog(this, "Updated record!", "Update record",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(this, 
                "Are you sure to delete this record?", "Delete record", 
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {

            this.deleteProduct();
            JOptionPane.showMessageDialog(this, "Deleted record!", "Delete record",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void butPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPhotoActionPerformed
        JFileChooser fc = new JFileChooser();
        int select = fc.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
            try {
                File photoFile = fc.getSelectedFile();
                labPhotoFilename.setText(photoFile.getCanonicalPath());
                ImageIcon iconPhoto = new ImageIcon(labPhotoFilename.getText());
                labPhoto.setIcon(iconPhoto);
            } catch (IOException ex) {
                Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_butPhotoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            this.getDataFile().getResultSet().last();
            this.updateView();
        } catch (SQLException ex) {
            Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLastActionPerformed
    /**
     * Get data file
     * @return data file
     */
    public MSAccess getDataFile() {
        return dataFile;
    }

    /**
     * Set data file
     * @param dataFile data file
     */
    public void setDataFile(MSAccess dataFile) {
        this.dataFile = dataFile;
    }

    /**
     * Get Image Icon
     * @return Image Icon
     */
    public ImageIcon getIconNoPhoto() {
        return iconNoPhoto;
    }

    /**
     * Set Image Icon
     * @param iconNoPhoto Image Icon
     */
    public void setIconNoPhoto(ImageIcon iconNoPhoto) {
        this.iconNoPhoto = iconNoPhoto;
    }
    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox ComType;
    private javax.swing.ButtonGroup GroupGenero;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton butPhoto;
    private com.toedter.calendar.JDateChooser dateDate_of_admission;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labId;
    private javax.swing.JLabel labPhoto;
    private javax.swing.JLabel labPhotoFilename;
    private javax.swing.JLabel labPrice;
    private javax.swing.JLabel lblDate_of_admission;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSex;
    private javax.swing.JPanel panCrud;
    private javax.swing.JPanel panDatosPersonales;
    private javax.swing.JTable table1;
    public javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

//    private void updateInterface() { 
//       if(this.getIndexProduct() != -1){
//           Product product = this.getProductList().get(this.getIndexProduct());
//           
//           txtId.setText("" + product.getId());
//           txtName.setText(product.getName());
////           txtApellido.setText(product.getApellido());
//           
//           labPath.setText((product.getPhoto().equals("")) ?
//                   this.path + "noPhoto.jpg" :
//                   product.getPhoto());
//                   ImageIcon photo = new ImageIcon(labPath.getText());
//                   labPhoto.setIcon(photo);
//       
//           
//           
//           
//            String seleccionado=(String)ComType.getSelectedItem();
//            setTitle(seleccionado);
//           
//           
//
//           dateDate_of_admission.setDate(product.getDate_of_admission());
//           txtPrice.setText("" + product.getPrice());
//
//
//           NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.getDefault());
//
//       }
//       else{
//           this.newInterface();
//       }
//    }
    
    /**
     * You prepare the interface to enter a new item
     */
//    private void newInterface() {
//        txtId.setText("");
//        txtName.setText("");
//
//        
//        labPath.setText(this.path + "noPhoto.jpg");
//        ImageIcon photo = new ImageIcon(labPath.getText());
//        labPhoto.setIcon(photo);
//        
//        ComType.setSelectedItem(box);
//        
//
//
//
//        dateDate_of_admission.setDate(new Date(105,0,2));
//        txtPrice.setText("");
//
//
//
//        
//        btnNew.setText("save");
//        btnFirst.setEnabled(false);
//        btnPrevious.setEnabled(false);
//        btnNext.setEnabled(false);
//        btnLast.setEnabled(false);
//        btnSearch.setEnabled(false);
//        btnDelete.setEnabled(false);    
//        btnUpdate.setEnabled(false);
//    }
    
    /**
     * You validate and store item 
     */

//    private void saveInterfaz() {
//       if (txtId.getText().equals("") 
//               || txtName.getText().equals("") 
//
//
//               
//               || (dateDate_of_admission.getDate() == null)
//               || txtPrice.getText().equals("")) {
//           JOptionPane.showMessageDialog(this, "Plaese fill the requiered fields","Error",JOptionPane.ERROR_MESSAGE);
//       }
//       else{
//           Product product = interface2Object();
//           this.getProductList().add(product);
//           this.setIndexProduct(this.getIndexProduct()+1);
//           
//           FlatFileProduct dataFile = new FlatFileProduct();
//           dataFile.writeFile(this.getProductList(),this.fileName,this.separator);
//           
//           NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.getDefault());
//
//           
//        btnNew.setText("new");
//        btnFirst.setEnabled(true);
//        btnPrevious.setEnabled(true);
//        btnNext.setEnabled(true);
//        btnLast.setEnabled(true);
//        btnSearch.setEnabled(true);
//        btnDelete.setEnabled(true);
//        btnUpdate.setEnabled(true);
//       }
//    }

    /**
     * You obtain data from the interface and passes it to an object 
     * @return Employee object 
     */
//    private Product interface2Object() {
//        Product product = new Product();
//        
//        product.setId(Long.parseLong(txtId.getText()));
//        product.setName(txtName.getText());
//
//        product.setPhoto(labPath.getText());
//        product.setKind_of_product(ComType.getSelectedItem().toString());
//
//
//        product.setDate_of_admission(dateDate_of_admission.getDate());
//        product.setPrice(Integer.parseInt(txtPrice.getText()));
//        
//        return product;
//    }
    
//    public void getBox(String boxType){
//        box = boxType;
//    }
    
     public void llenarLista(){
        Product tAux;    
        DefaultTableModel modelo;
        String columnas [] = new String []{"Id","Name","kind_of_product","price","date_of_admission"}; 
        modelo = new DefaultTableModel(null,columnas);
        Object datos [] = new Object[5];
        for (int i = 0; i< cl.getTamanio(); i++) {
        tAux= new Product();
        tAux = (Product)cl.getElement(i);
        
        datos[0]= tAux.getId();
        datos[1]= tAux.getName();
        datos[2]= tAux.getType();
        datos[3]= tAux.getPrice();
        datos[4]= tAux.getDate_of_admission();
       
        modelo.addRow(datos);
        }
        table1.setModel(modelo);
    }           

    

    private void selectProduct() {
         String query = "SELECT * FROM Product";
        if (this.getDataFile().execute(query)) {
            try {
                this.getDataFile().getResultSet().next();
                this.updateView();
            } catch (SQLException ex) {
                Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void newView() {
        txtId.setText("");
        txtName.setText("");
        ComType.setSelectedItem("");
        //txtLastname.setText("");
        labPhotoFilename.setText("");
        labPhoto.setIcon(this.getIconNoPhoto());
        //radFemale.setSelected(true);
        dateDate_of_admission.setDate(new Date(90, 0, 1));
        //datHired.setDate(new Date(108, 6, 15));
        txtPrice.setText("");
        
//        labAge.setText("Age: ");
//        labOld.setText("Old: ");
//        labBenefits.setText("Benefits: ");
        
        btnNew.setText("Save");
        btnFirst.setEnabled(false);
        btnPrevious.setEnabled(false);
        btnNext.setEnabled(false);
        btnLast.setEnabled(false);
        btnSearch.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    private boolean validateView() {
         boolean validate = !(txtId.getText().equals("")
                || txtName.getText().equals("") 
                || ComType.getSelectedItem().equals("")
                || (dateDate_of_admission.getDate() == null)
                //|| (datHired.getDate() == null)
                || txtPrice.getText().equals(""));
        return validate;
    }

    private void insertProduct() {
        Product product = this.view2Object();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String query = "INSERT INTO Product "
                + "(Id, NameProduct, Kind_of_product, photo, date_of_admission, price) "
                + "VALUES ("
                + product.getId() + ", '"
                + product.getName()+ "', '"
                + product.getKind_of_product()+ "', '"
                + product.getPhoto() + "', #"         //"', "
               // + product.getGender() + ", #"
                + dateFormat.format(product.getDate_of_admission()) + "#, "
                //+ dateFormat.format(product.getHiredDate()) + "#, "
                + product.getPrice() + ")";
        if (this.getDataFile().execute(query)) {
            this.selectProduct();
            this.searchProduct(product.getId());
        }
    }
    
     private Product view2Object() {
        Product product = new Product();

        product.setId(Long.parseLong(txtId.getText()));
        product.setName(txtName.getText());
        product.setKind_of_product(ComType.getSelectedItem().toString());
        product.setPhoto(labPhotoFilename.getText());
        //product.setGender(radFemale.isSelected() ? 0 : 1);
        product.setDate_of_admission(dateDate_of_admission.getDate());
        //product.setHiredDate(datHired.getDate());
        product.setPrice(Integer.parseInt(txtPrice.getText()));
        
        return product;
    }

    private void updateProduct() {
         Product product = this.view2Object();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String query = "UPDATE Product SET "
                + "NameProduct = '" + product.getName()+ "', "
                + "Kind_of_product = '" + product.getKind_of_product()+ "', "
                + "photo = '" + product.getPhoto() + "', "
              //+ "gender = " + product.getGender() + ", "
                + "date_of_admission = #" + dateFormat.format(product.getDate_of_admission()) + "#, "
              //  + "hiredDate = #" + dateFormat.format(product.getHiredDate()) + "#, "
                + "price = " + product.getPrice()+ " "
                + "WHERE id = " + product.getId();
        if (this.getDataFile().execute(query)) {
            this.selectProduct();
            this.searchProduct(product.getId());
        }
    }

    private void deleteProduct() {
        Product product = this.view2Object();
        String query = "DELETE * FROM Product WHERE id = " + product.getId();
        if (this.getDataFile().execute(query)) {
            this.selectProduct();
        } 
    }

    private void updateView() {
          if (this.getDataFile().getResultSet() == null) {
            this.newView();
        }
        else {
            this.object2View();
        } //To change body of generated methods, choose Tools | Templates.
    }

    private void object2View() {
         Product product = new Product();
        try {
            product.setId(this.getDataFile().getResultSet().getLong("id"));
            product.setName(this.getDataFile().getResultSet().getString("NameProduct"));
            product.setKind_of_product(this.getDataFile().getResultSet().getString("Kind_of_product"));
            product.setPhoto(
                    (this.getDataFile().getResultSet().getString("photo") == null) 
                            ? "" : this.getDataFile().getResultSet().getString("photo"));
            //product.setGender(this.getDataFile().getResultSet().getInt("gender"));
            product.setDate_of_admission(this.getDataFile().getResultSet().getDate("date_of_admission"));
            //product.setHiredDate(this.getDataFile().getResultSet().getDate("hiredDate"));
            product.setPrice(this.getDataFile().getResultSet().getInt("price"));

            this.object2View(product);
        } catch (SQLException ex) {
            Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchProduct(long id) {
        boolean find = false;
        try {
            if (this.getDataFile().getResultSet() != null) {
                Long lastId = this.getDataFile().getResultSet().getLong("id");
                this.getDataFile().getResultSet().beforeFirst();
                while (this.getDataFile().getResultSet().next()) {
                    if (this.getDataFile().getResultSet().getLong("id") == id) {
                        find = true;
                        break;
                    }
                }
                if (find) {
                    this.updateView();
                }
                else {
                    this.getDataFile().getResultSet().first();
                    this.searchProduct(lastId);
                    JOptionPane.showMessageDialog(this, "Product " + id + " was not found!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(InterfazProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void object2View(Product product) {
        txtId.setText("" + product.getId());
        txtName.setText(product.getName());
        ComType.setSelectedItem(product.getDate_of_admission());
        //txtLastname.setText(product.getLastname());

        if (product.getPhoto().equals("")) {
            labPhotoFilename.setText("");
            labPhoto.setIcon(this.getIconNoPhoto());
        }
        else {
            labPhotoFilename.setText(product.getPhoto());
            ImageIcon iconPhoto = new ImageIcon(labPhotoFilename.getText());
            labPhoto.setIcon(iconPhoto);
        }
        
        //radFemale.setSelected(product.getGender() == 0);
        dateDate_of_admission.setDate(product.getDate_of_admission());
        //datHired.setDate(product.getHiredDate());
        txtPrice.setText("" + product.getPrice());

//        labAge.setText("Age: " + product.getAge() + " years");
//        labOld.setText("Old: " + product.getOld() + " years");
//        NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.getDefault());
//        labBenefits.setText("Benefits: " + nf.format(product.getBenefits()));   
    }
    
    
    
}
